title: "Hằng Lê's Resume"
logo: asset/Hang Le.jpeg
description: Personal resume and portfolio
#show_downloads: false
theme: jekyll-theme-minimal

# Enable navigation links for different pages
header_pages:
  - index.md
  - projects.md
