title: "My Portfolio"
logo: asset/Hang Le.jpeg
description: Personal resume and portfolio
#show_downloads: false
theme: jekyll-theme-cayman

# Enable navigation links for different pages
navbar:
  - name: Home
    link: /
  - name: Projects
    link: /projects
# Include custom CSS
custom_css:
  - asset/style.css
