title: "My Portfolio"
logo: assets/Hang Le.jpeg
description: Personal resume and portfolio
#show_downloads: false
theme: jekyll-theme-cayman

# Custom Navigation Links
header_pages:
  - index.md
  - projects.md
# Include custom CSS
custom_css:
  - assets/style.css
